apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quickstarts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quickstarts
    app.kubernetes.io/part-of: quickstarts
  name: quickstarts
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: quickstarts
status:
  loadBalancer: {}
